name: Darling CI

on: [push, pull_request]

jobs:
  build-deb:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4

    - name: Checkout submodules
      shell: bash
      run: |
        git clone --recursive https://github.com/darlinghq/darling.git
        cd darling

    - name: Install dependencies
      run: |
        echo "deb http://apt.llvm.org/buster/ llvm-toolchain-buster main" | sudo tee /etc/apt/sources.list
        echo "deb-src http://apt.llvm.org/buster/ llvm-toolchain-buster main" | sudo tee /etc/apt/sources.list
        echo "deb http://apt.llvm.org/buster/ llvm-toolchain-buster-10 main" | sudo tee /etc/apt/sources.list
        echo "deb-src http://apt.llvm.org/buster/ llvm-toolchain-buster-10 main" | sudo tee /etc/apt/sources.list
        echo "deb http://apt.llvm.org/buster/ llvm-toolchain-buster-12 main" | sudo tee /etc/apt/sources.list
        echo "deb-src http://apt.llvm.org/buster/ llvm-toolchain-buster-12 main" | sudo tee /etc/apt/sources.list
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        sudo apt-get update && sudo apt-get install devscripts equivs debhelper
        sudo apt-get install clang-12
        export CMAKE_C_COMPILER=clang-12
        export CMAKE_CXX_COMPILER=clang++-12
        sudo mk-build-deps -i -r -t "apt-get --no-install-recommends -y" debian/control
        
        

    # see https://github.com/actions/virtual-environments/issues/2606#issuecomment-772683150
    - name: Free up space
      run: |
        sudo rm -rf /usr/share/dotnet

    - name: Build DEBs
      run: |
        ./tools/debian/make-deb

    - name: Move DEBs
      run: |
        mkdir dist && mv ../*.deb dist

    - name: Upload artifacts
      uses: actions/upload-artifact@v4.1.0
      with:
        name: 'debs'
        path: dist/

  build-dsc:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4

    - name: Checkout submodules
      shell: bash
      run: |
        git submodule update --init --recursive --depth=1

    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install devscripts equivs debhelper

    - name: Build DSCs
      run: |
        ./tools/debian/make-deb --dsc

    - name: Move DSCs
      run: |
        mkdir source && mv ../*~$(lsb_release -cs).* source

    - name: Upload artifacts
      uses: actions/upload-artifact@v4.1.0
      with:
        name: 'source'
        path: source/
